export const TitanPartMap = {
    'Armor Leg Right': 'ArmorLegUpperRight',
    'Armor Hand Left': 'ArmorHandLeft',
    'Armor Hand Right': 'ArmorHandRight',
    'Armor Leg Left': 'ArmorLegUpperLeft',
    'Armor Chest': 'ArmorChestUpper',
    'Armor Arm Right': 'ArmorArmUpperRight',
    'Armor Arm Left': 'ArmorArmUpperLeft',
    'Armor Head': 'ArmorHead',
    'Body Leg Right': 'BodyLegUpperRight',
    'Body Hand Left': 'BodyHandLeft',
    'Body Hand Right': 'BodyHandRight',
    'Body Leg Left': 'BodyLegUpperLeft',
    'Body Chest': 'BodyChestUpper',
    'Body Arm Right': 'BodyArmUpperRight',
    'Body Arm Left': 'BodyArmUpperLeft',
    'Body Head': 'BodyHead',
    'Skeleton Leg Right': 'SkeletonLegUpperRight',
    'Skeleton Hand Left': 'SkeletonHandLeft',
    'Skeleton Hand Right': 'SkeletonHandRight',
    'Skeleton Leg Left': 'SkeletonLegUpperLeft',
    'Skeleton Chest': 'SkeletonChestUpper',
    'Skeleton Arm Right': 'SkeletonArmUpperRight',
    'Skeleton Arm Left': 'SkeletonArmUpperLeft',
    'Skeleton Head': 'SkeletonHead',

    Unknown: 'Unknown',
} as const;

export const RaidCardMap = {
    MoonBeam: 'MoonBeam',
    Fragmentize: 'Fragmentize',
    SkullBash: 'SkullBash',
    RazorWind: 'RazorWind',
    WhipOfLightning: 'WhipOfLightning',
    ClanshipBarrage: 'BurstCount',
    PurifyingBlast: 'Purify',
    PsychicShackles: 'LimbBurst',
    FlakShot: 'FlakShot',
    CosmicHaymaker: 'Haymaker',
    ChainOfVengeance: 'ChainLightning',
    MirrorForce: 'MirrorForce',
    CelestialStatic: 'CelestialStatic',
    BlazingInferno: 'BurningAttack',
    AcidDrench: 'PoisonAttack',
    DecayingStrike: 'DecayingAttack',
    FusionBomb: 'Fuse',
    GrimShadow: 'Shadow',
    ThrivingPlague: 'PlagueAttack',
    Radioactivity: 'Disease',
    RavenousSwarm: 'Swarm',
    RuinousRain: 'RuinousRust',
    CorrosiveBubbles: 'PowerBubble',
    Maelstrom: 'RuneAttack',
    CrushingInstinct: 'ExecutionersAxe',
    InsanityVoid: 'CrushingVoid',
    RancidGas: 'MentalFocus',
    InspiringForce: 'ImpactAttack',
    SoulFire: 'InnerTruth',
    VictoryMarch: 'FinisherAttack',
    PrismaticRift: 'SuperheatMetal',
    AncestralFavor: 'BurstBoost',
    GraspingVines: 'LimbSupport',
    TotemOfPower: 'TotemFairySkill',
    TeamTactics: 'TeamTactics',
    SkeletalSmash: 'SpinalTap',
    AstralEcho: 'AstralEcho',
    TapDamage: 'TapDamage',
    Wildcard: 'Wildcard',
} as const;
