export const TitanPartMap = {
    'Armor Leg Right': 'ArmorLegUpperRight',
    'Armor Hand Left': 'ArmorHandLeft',
    'Armor Hand Right': 'ArmorHandRight',
    'Armor Leg Left': 'ArmorLegUpperLeft',
    'Armor Chest': 'ArmorChestUpper',
    'Armor Arm Right': 'ArmorArmUpperRight',
    'Armor Arm Left': 'ArmorArmUpperLeft',
    'Armor Head': 'ArmorHead',
    'Body Leg Right': 'BodyLegUpperRight',
    'Body Hand Left': 'BodyHandLeft',
    'Body Hand Right': 'BodyHandRight',
    'Body Leg Left': 'BodyLegUpperLeft',
    'Body Chest': 'BodyChestUpper',
    'Body Arm Right': 'BodyArmUpperRight',
    'Body Arm Left': 'BodyArmUpperLeft',
    'Body Head': 'BodyHead',
    'Skeleton Leg Right': 'SkeletonLegUpperRight',
    'Skeleton Hand Left': 'SkeletonHandLeft',
    'Skeleton Hand Right': 'SkeletonHandRight',
    'Skeleton Leg Left': 'SkeletonLegUpperLeft',
    'Skeleton Chest': 'SkeletonChestUpper',
    'Skeleton Arm Right': 'SkeletonArmUpperRight',
    'Skeleton Arm Left': 'SkeletonArmUpperLeft',
    'Skeleton Head': 'SkeletonHead',
} as const;

export const RaidCardMap = {
    MoonBeam: { name: 'MoonBeam', type: 'Burst' },
    Fragmentize: { name: 'Fragmentize', type: 'Burst' },
    SkullBash: { name: 'SkullBash', type: 'Burst' },
    RazorWind: { name: 'RazorWind', type: 'Burst' },
    WhipOfLightning: { name: 'WhipOfLightning', type: 'Burst' },
    ClanshipBarrage: { name: 'BurstCount', type: 'Burst' },
    PurifyingBlast: { name: 'Purify', type: 'Burst' },
    PsychicShackles: { name: 'LimbBurst', type: 'Burst' },
    FlakShot: { name: 'FlakShot', type: 'Burst' },
    CosmicHaymaker: { name: 'Haymaker', type: 'Burst' },
    ChainOfVengeance: { name: 'ChainLightning', type: 'Burst' },
    MirrorForce: { name: 'MirrorForce', type: 'Burst' },
    CelestialStatic: { name: 'CelestialStatic', type: 'Burst' },
    BlazingInferno: { name: 'BurningAttack', type: 'Affliction' },
    AcidDrench: { name: 'PoisonAttack', type: 'Affliction' },
    DecayingStrike: { name: 'DecayingAttack', type: 'Affliction' },
    FusionBomb: { name: 'Fuse', type: 'Affliction' },
    GrimShadow: { name: 'Shadow', type: 'Affliction' },
    ThrivingPlague: { name: 'PlagueAttack', type: 'Affliction' },
    Radioactivity: { name: 'Disease', type: 'Affliction' },
    RavenousSwarm: { name: 'Swarm', type: 'Affliction' },
    RuinousRain: { name: 'RuinousRust', type: 'Affliction' },
    CorrosiveBubbles: { name: 'PowerBubble', type: 'Affliction' },
    Maelstrom: { name: 'RuneAttack', type: 'Affliction' },
    CrushingInstinct: { name: 'ExecutionersAxe', type: 'Support' },
    InsanityVoid: { name: 'CrushingVoid', type: 'Support' },
    RancidGas: { name: 'MentalFocus', type: 'Support' },
    InspiringForce: { name: 'ImpactAttack', type: 'Support' },
    SoulFire: { name: 'InnerTruth', type: 'Support' },
    VictoryMarch: { name: 'FinisherAttack', type: 'Support' },
    PrismaticRift: { name: 'SuperheatMetal', type: 'Support' },
    AncestralFavor: { name: 'BurstBoost', type: 'Support' },
    GraspingVines: { name: 'LimbSupport', type: 'Support' },
    TotemOfPower: { name: 'TotemFairySkill', type: 'Support' },
    TeamTactics: { name: 'TeamTactics', type: 'Support' },
    SkeletalSmash: { name: 'SpinalTap', type: 'Support' },
    AstralEcho: { name: 'AstralEcho', type: 'Support' },
    TapDamage: { name: 'TapDamage', type: 'Support' },
    Wildcard: { name: 'Wildcard', type: 'Support' },
} as const;
