export const TitanPartMap = {
    'Armor Leg Right': 'ArmorLegUpperRight',
    'Armor Hand Left': 'ArmorHandLeft',
    'Armor Hand Right': 'ArmorHandRight',
    'Armor Leg Left': 'ArmorLegUpperLeft',
    'Armor Chest': 'ArmorChestUpper',
    'Armor Arm Right': 'ArmorArmUpperRight',
    'Armor Arm Left': 'ArmorArmUpperLeft',
    'Armor Head': 'ArmorHead',
    'Body Leg Right': 'BodyLegUpperRight',
    'Body Hand Left': 'BodyHandLeft',
    'Body Hand Right': 'BodyHandRight',
    'Body Leg Left': 'BodyLegUpperLeft',
    'Body Chest': 'BodyChestUpper',
    'Body Arm Right': 'BodyArmUpperRight',
    'Body Arm Left': 'BodyArmUpperLeft',
    'Body Head': 'BodyHead',
    'Skeleton Leg Right': 'SkeletonLegUpperRight',
    'Skeleton Hand Left': 'SkeletonHandLeft',
    'Skeleton Hand Right': 'SkeletonHandRight',
    'Skeleton Leg Left': 'SkeletonLegUpperLeft',
    'Skeleton Chest': 'SkeletonChestUpper',
    'Skeleton Arm Right': 'SkeletonArmUpperRight',
    'Skeleton Arm Left': 'SkeletonArmUpperLeft',
    'Skeleton Head': 'SkeletonHead',
} as const;
